### ISSUE TITLE
DateTime objects not fully visible

### ISSUE THREAD

**Issue by B0bbyD0llar** [chevere/var-dump#6]
Hello,

datetime objects not fully shown.

i get:
```
Arg:0 DateTimeImmutable#150
```

**Comment by rodber** [comment]
Here: https://3v4l.org/KEUaA which is known to be an issue since 2016: https://externals.io/message/93777

VarDump uses reflection and I'm afraid that the problem is with all internal classes provided by the core library or extensions. These don't always add the reflection data values.

I've also found and report this issue with Ds\Map: https://github.com/php-ds/ext-ds/issues/190, I think that is just futile trying to get all internal classes to support PHP reflection (as they should). I'm sure that this inconsistency needs to be considered as a language feature and I wasn't able to find any single note or commentary on php manual about reflection being this unreliable. It seems that for internal objects developers must not consider it at all. PHP is reflective, but only applies within user land code. 

My conclusion is that this package should use [debug info](https://www.php.net/manual/en/language.oop5.magic.php#object.debuginfo), but that can't be accessed when dealing with internal objects.

**Comment by rodber** [comment]
I've pulled off some tricks, I managed to get this:

```sh
❯ php demo/demo.php                                  
^ DateTime @1653052617 {#2
  date: 2022-05-20 10:16:57.625783 America/Halifax (-03:00)
}

vd()
------------------------------------------------------------
demo/demo.php:31

Arg•0 DateTime#2
 public date string 2022-05-20 10:16:57.625783 (length=26)
 public timezone_type integer 3 (length=1)
 public timezone string America/Halifax (length=15)
------------------------------------------------------------
```

As you may notice, internal classes are now printing public available properties. On top you can see the output of symfony's `dump` and below chevere's `vd`.
